export const cities = [
  {
    number: 1,
    title: 'Fundação da civilização',
    story: 'Através de um plano de colonização interestelar, os humanos criaram uma nova civilização em um planeta chamado Aida<br /><br /> Lá, construíram a Torre da Fantasia a fim de minerar Omnium, uma energia potente e misteriosa contida no cometa Mara.',
    iconImg: '/assets/images/page3/p3-img1-m.png',
    backgroundImage: (selected:number) => (selected === 1 ? "url('/assets/images/page3/p3-btn-after-a.png')" : "url('/assets/images/page3/p3-btn-bg.png')"),
    size: (selected:number) => (selected === 1 ? '100px' : '70px'),
    beforeSize: (selected:number) => (selected === 1 ? '120px' : '90px'),
    bottom: '25%',
    right: '640px',
  },
  {
    number: 2,
    title: 'Fundação da civilização',
    story: 'Através de um plano de colonização interestelar, os humanos criaram uma nova civilização em um planeta chamado Aida<br /><br /> Lá, construíram a Torre da Fantasia a fim de minerar Omnium, uma energia potente e misteriosa contida no cometa Mara.',
    iconImg: '/assets/images/page3/p3-img2-m.png',
    backgroundImage: (selected:number) => (selected === 2 ? "url('/assets/images/page3/p3-btn-after-a.png')" : "url('/assets/images/page3/p3-btn-bg.png')"),
    size: (selected:number) => (selected === 2 ? '100px' : '70px'),
    beforeSize: (selected:number) => (selected === 2 ? '120px' : '90px'),
    bottom: '43%',
    right: '600px',
  },
  {
    number: 3,
    title: 'Fundação da civilização',
    story: 'Através de um plano de colonização interestelar, os humanos criaram uma nova civilização em um planeta chamado Aida<br /><br /> Lá, construíram a Torre da Fantasia a fim de minerar Omnium, uma energia potente e misteriosa contida no cometa Mara.',
    iconImg: '/assets/images/page3/p3-img3-m.png',
    backgroundImage: (selected:number) => (selected === 3 ? "url('/assets/images/page3/p3-btn-after-a.png')" : "url('/assets/images/page3/p3-btn-bg.png')"),
    size: (selected:number) => (selected === 3 ? '100px' : '70px'),
    beforeSize: (selected:number) => (selected === 3 ? '120px' : '90px'),
    bottom: '59%',
    right: '520px',
  },
];
