import * as Nemesis from "characters/nemesis";
import * as Meryl from "characters/meryl";
import * as Claudia from "characters/claudia";
import * as Samir from "characters/samir";
import { ICharacter } from "./types";

export const characters = [
    {
    number: 0,
    name: "Meryl",
    hueRotate: "0deg",
    fade: Meryl.Fade.src,
    fade_M: Meryl.Fade_M.src,
    img: Meryl.Main.src,
    img_M: Meryl.Main_M.src,
    active: Meryl.Active.src,
    inactive: Meryl.Inactive.src,
    weapon: Meryl.Weapon.src,
    weapon_M: Meryl.Weapon_M.src,
    tab: Meryl.Tab.src,
    mainColors: { primary: "#17d3fe" ,secondary:"#24555c" },
    audio: Meryl.Audio,
     },
    {
      number: 1,
      name: "Nemesis",
      fade: Nemesis.Fade.src,
      fade_M: Nemesis.Fade_M.src,
      img: Nemesis.Main.src,
      img_M: Nemesis.Main_M.src,
      active: Nemesis.Active.src,
      inactive: Nemesis.Inactive.src,
      weapon: Nemesis.Weapon.src,
      weapon_M: Nemesis.Weapon_M.src,
      tab: Nemesis.Tab.src,
      hueRotate: "-203deg",
      mainColors: { primary: "#fb7ca1",secondary:"#8c445c" },
      audio: Nemesis.Audio,
    },
    {
      number: 2,
      name: "Claudia",
      hueRotate: "200deg",
      fade: Claudia.Fade.src,
      fade_M: Claudia.Fade_M.src,
      img: Claudia.Main.src,
      img_M: Claudia.Main_M.src,
      active: Claudia.Active.src,
      inactive: Claudia.Inactive.src,
      weapon: Claudia.Weapon.src,
      weapon_M: Claudia.Weapon_M.src,
      tab: Claudia.Tab.src,
      mainColors: { primary: "#fc9831" ,secondary:"#a46c34" },
      audio: Claudia.Audio,
    },
    {
      number: 3,
      hueRotate: "227deg",
      name: "Samir",
      fade: Samir.Fade.src,
      fade_M: Samir.Fade_M.src,
      img: Samir.Main.src,
      img_M: Samir.Main_M.src,
      active: Samir.Active.src,
      inactive: Samir.Inactive.src,
      weapon: Samir.Weapon.src,
      weapon_M: Samir.Weapon_M.src,
      tab: Samir.Tab.src,
      mainColors: { primary: "#dbb41c",secondary:"#66512a" },
      audio: Samir.Audio,
    },
  ] as ICharacter[];
  